# R for travis: see documentation at https://docs.travis-ci.org/user/languages/r

language: R

os:
  - linux
  - osx

sudo: false

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
  deploy:
    provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true

cache: packages

addons:
  apt:
    packages:
      - libxml2-dev # an xml2 dependency
